"""
Auto-generated field name constants from game_state.schema.json

DO NOT EDIT - This file is generated by:
  python scripts/schema/generate_field_constants.py

Run this script after modifying the schema to regenerate constants.
"""

from typing import Final

# Top-level game state fields
TOP_LEVEL_FIELDS: Final = {
    "action_resolution": "action_resolution",
    "combat_state": "combat_state",
    "complications": "complications",
    "custom_campaign_state": "custom_campaign_state",
    "debug_mode": "debug_mode",
    "dual_mode": "dual_mode",
    "encounter_state": "encounter_state",
    "faction_minigame": "faction_minigame",
    "faction_updates": "faction_updates",
    "game_state": "game_state",
    "game_state_version": "game_state_version",
    "item_registry": "item_registry",
    "last_living_world_time": "last_living_world_time",
    "last_living_world_turn": "last_living_world_turn",
    "last_state_update_timestamp": "last_state_update_timestamp",
    "location": "location",
    "npc_agendas": "npc_agendas",
    "npc_data": "npc_data",
    "pending_instruction_hints": "pending_instruction_hints",
    "planning_block": "planning_block",
    "player_character_data": "player_character_data",
    "player_turn": "player_turn",
    "rewards_pending": "rewards_pending",
    "rumors": "rumors",
    "scene_event": "scene_event",
    "session_id": "session_id",
    "social_hp_challenge": "social_hp_challenge",
    "time_events": "time_events",
    "time_pressure_warnings": "time_pressure_warnings",
    "time_sensitive_events": "time_sensitive_events",
    "turn_number": "turn_number",
    "user_settings": "user_settings",
    "world_data": "world_data",
    "world_events": "world_events",
    "world_resources": "world_resources",
}

# Nested definition fields
ACTIONRESOLUTION_FIELDS: Final = {
    "audit_flags": "audit_flags",
    "interpreted_as": "interpreted_as",
    "mechanics": "mechanics",
    "narrative_outcome": "narrative_outcome",
    "player_input": "player_input",
    "reinterpreted": "reinterpreted",
}

ACTIONRESOLUTIONROLL_FIELDS: Final = {
    "dc": "dc",
    "dc_category": "dc_category",
    "dc_reasoning": "dc_reasoning",
    "die_type": "die_type",
    "margin": "margin",
    "modifier": "modifier",
    "notation": "notation",
    "outcome": "outcome",
    "purpose": "purpose",
    "result": "result",
    "success": "success",
    "total": "total",
}

ARCMILESTONE_FIELDS: Final = {
    "completed_at": "completed_at",
    "notes": "notes",
    "phase": "phase",
    "progress": "progress",
    "status": "status",
    "updated_at": "updated_at",
}

CAMPAIGNTIER_FIELDS: Final = {
}

CHAPTERDATA_FIELDS: Final = {
    "bonus_content": "bonus_content",
    "chapter_metadata": "chapter_metadata",
    "current_chapter": "current_chapter",
}

CHARACTER_FIELDS: Final = {
    "active_effects": "active_effects",
    "age": "age",
    "aliases": "aliases",
    "alignment": "alignment",
    "attributes": "attributes",
    "background": "background",
    "base_attributes": "base_attributes",
    "class": "class",
    "class_name": "class_name",
    "combat_stats": "combat_stats",
    "core_memories": "core_memories",
    "current_location": "current_location",
    "death_saves": "death_saves",
    "display_name": "display_name",
    "entity_id": "entity_id",
    "entity_type": "entity_type",
    "equipment": "equipment",
    "equipped_items": "equipped_items",
    "gender": "gender",
    "health": "health",
    "hp_current": "hp_current",
    "hp_max": "hp_max",
    "inventory": "inventory",
    "knowledge": "knowledge",
    "level": "level",
    "mbti": "mbti",
    "name": "name",
    "proficiency_bonus": "proficiency_bonus",
    "race": "race",
    "recent_decisions": "recent_decisions",
    "relationships": "relationships",
    "resources": "resources",
    "spells_known": "spells_known",
    "stats": "stats",
    "status": "status",
    "status_conditions": "status_conditions",
    "string_id": "string_id",
    "visibility": "visibility",
    "xp": "xp",
}

COMBATSTATE_FIELDS: Final = {
    "active_combatant": "active_combatant",
    "combat_phase": "combat_phase",
    "combat_session_id": "combat_session_id",
    "combat_summary": "combat_summary",
    "combatants": "combatants",
    "in_combat": "in_combat",
    "initiative_order": "initiative_order",
    "participants": "participants",
    "rewards_processed": "rewards_processed",
    "round": "round",
    "round_number": "round_number",
}

COMBATANTSTATE_FIELDS: Final = {
    "concentration_spell": "concentration_spell",
    "has_acted": "has_acted",
    "hp_current": "hp_current",
    "hp_max": "hp_max",
    "reactions_used": "reactions_used",
    "role": "role",
    "status": "status",
    "type": "type",
}

COMPANIONARC_FIELDS: Final = {
    "arc_type": "arc_type",
    "callbacks": "callbacks",
    "history": "history",
    "phase": "phase",
}

CUSTOMCAMPAIGNSTATE_FIELDS: Final = {
    "active_constraints": "active_constraints",
    "active_missions": "active_missions",
    "arc_milestones": "arc_milestones",
    "attribute_system": "attribute_system",
    "budget_warnings_shown": "budget_warnings_shown",
    "campaign_tier": "campaign_tier",
    "character_creation_completed": "character_creation_completed",
    "character_creation_in_progress": "character_creation_in_progress",
    "character_creation_stage": "character_creation_stage",
    "companion_arcs": "companion_arcs",
    "core_memories": "core_memories",
    "divine_potential": "divine_potential",
    "divine_upgrade_available": "divine_upgrade_available",
    "faction_minigame": "faction_minigame",
    "god_mode": "god_mode",
    "god_mode_directives": "god_mode_directives",
    "last_location": "last_location",
    "last_story_mode_sequence_id": "last_story_mode_sequence_id",
    "level_up_cancelled": "level_up_cancelled",
    "level_up_complete": "level_up_complete",
    "level_up_in_progress": "level_up_in_progress",
    "level_up_pending": "level_up_pending",
    "multiverse_upgrade_available": "multiverse_upgrade_available",
    "next_companion_arc_turn": "next_companion_arc_turn",
    "player_character_data_extras": "player_character_data_extras",
    "progression": "progression",
    "reputation": "reputation",
    "sanctuary_mode": "sanctuary_mode",
    "success_streak": "success_streak",
    "universe_control": "universe_control",
    "world_events": "world_events",
}

ENCOUNTERSTATE_FIELDS: Final = {
    "encounter_active": "encounter_active",
    "encounter_completed": "encounter_completed",
    "encounter_summary": "encounter_summary",
    "encounter_type": "encounter_type",
    "rewards_processed": "rewards_processed",
}

ENTITYSTATUS_FIELDS: Final = {
}

ENTITYTYPE_FIELDS: Final = {
}

FACTIONMINIGAME_FIELDS: Final = {
    "buildings": "buildings",
    "enabled": "enabled",
    "faction_power": "faction_power",
    "ranking": "ranking",
    "resources": "resources",
    "turn_number": "turn_number",
    "tutorial_completed": "tutorial_completed",
    "units": "units",
}

FACTIONRESOURCES_FIELDS: Final = {
    "gold": "gold",
    "territory": "territory",
}

FACTIONUNITS_FIELDS: Final = {
    "elite_avg_level": "elite_avg_level",
    "elites": "elites",
    "soldiers": "soldiers",
    "spies": "spies",
}

GODMODEDIRECTIVE_FIELDS: Final = {
    "added": "added",
    "rule": "rule",
}

HEALTHSTATUS_FIELDS: Final = {
    "conditions": "conditions",
    "death_saves": "death_saves",
    "hp": "hp",
    "hp_max": "hp_max",
    "temp_hp": "temp_hp",
}

LEGACYINITIATIVEENTRY_FIELDS: Final = {
    "initiative": "initiative",
    "name": "name",
    "type": "type",
}

LOCATION_FIELDS: Final = {
    "aliases": "aliases",
    "connected_locations": "connected_locations",
    "description": "description",
    "display_name": "display_name",
    "entities_present": "entities_present",
    "entity_id": "entity_id",
    "entity_type": "entity_type",
    "environmental_effects": "environmental_effects",
}

NPC_FIELDS: Final = {
}

PLANNINGBLOCK_FIELDS: Final = {
    "choice_id": "choice_id",
    "choices": "choices",
    "chosen_choice": "chosen_choice",
    "context": "context",
    "plan_quality": "plan_quality",
    "thinking": "thinking",
}

PLANNINGCHOICE_FIELDS: Final = {
    "confidence": "confidence",
    "cons": "cons",
    "description": "description",
    "freeze_time": "freeze_time",
    "id": "id",
    "pros": "pros",
    "risk_level": "risk_level",
    "switch_to_story_mode": "switch_to_story_mode",
    "text": "text",
}

PLANNINGCHOICELEGACY_FIELDS: Final = {
    "confidence": "confidence",
    "cons": "cons",
    "description": "description",
    "freeze_time": "freeze_time",
    "pros": "pros",
    "risk_level": "risk_level",
    "switch_to_story_mode": "switch_to_story_mode",
    "text": "text",
}

PLAYERCHARACTER_FIELDS: Final = {
}

REWARDSPENDING_FIELDS: Final = {
    "gold": "gold",
    "items": "items",
    "level_up_available": "level_up_available",
    "new_level": "new_level",
    "processed": "processed",
    "source": "source",
    "source_id": "source_id",
    "xp": "xp",
}

SANCTUARYMODE_FIELDS: Final = {
    "activated_turn": "activated_turn",
    "active": "active",
    "arc": "arc",
    "broken": "broken",
    "broken_reason": "broken_reason",
    "broken_turn": "broken_turn",
    "expired": "expired",
    "expired_turn": "expired_turn",
    "expires_turn": "expires_turn",
    "original_scale": "original_scale",
    "scale": "scale",
}

SOCIALHPCHALLENGE_FIELDS: Final = {
    "cooldown_remaining": "cooldown_remaining",
    "cooldown_until_hour": "cooldown_until_hour",
    "npc_id": "npc_id",
    "npc_name": "npc_name",
    "npc_tier": "npc_tier",
    "objective": "objective",
    "request_severity": "request_severity",
    "resistance_shown": "resistance_shown",
    "roll_dc": "roll_dc",
    "roll_result": "roll_result",
    "skill_used": "skill_used",
    "social_hp": "social_hp",
    "social_hp_damage": "social_hp_damage",
    "social_hp_max": "social_hp_max",
    "status": "status",
    "successes": "successes",
    "successes_needed": "successes_needed",
}

STATS_FIELDS: Final = {
    "charisma": "charisma",
    "constitution": "constitution",
    "dexterity": "dexterity",
    "intelligence": "intelligence",
    "strength": "strength",
    "wisdom": "wisdom",
}

STORYENTRY_FIELDS: Final = {
    "action_resolution": "action_resolution",
    "actor": "actor",
    "debug_info": "debug_info",
    "dice_rolls": "dice_rolls",
    "directives": "directives",
    "god_mode_response": "god_mode_response",
    "mode": "mode",
    "narrative": "narrative",
    "part": "part",
    "planning_block": "planning_block",
    "resources": "resources",
    "session_header": "session_header",
    "state_updates": "state_updates",
    "text": "text",
    "timestamp": "timestamp",
    "world_events": "world_events",
}

VISIBILITY_FIELDS: Final = {
}

WORLDDATA_FIELDS: Final = {
    "current_location": "current_location",
    "current_location_name": "current_location_name",
    "location": "location",
    "locations": "locations",
    "weather": "weather",
    "world_events": "world_events",
    "world_time": "world_time",
}

WORLDEVENT_FIELDS: Final = {
    "action": "action",
    "actor": "actor",
    "discovered_turn": "discovered_turn",
    "discovery_condition": "discovery_condition",
    "event_type": "event_type",
    "location": "location",
    "outcome": "outcome",
    "player_aware": "player_aware",
    "player_impact": "player_impact",
    "status": "status",
}

WORLDTIME_FIELDS: Final = {
    "day": "day",
    "hour": "hour",
    "microsecond": "microsecond",
    "minute": "minute",
    "month": "month",
    "second": "second",
    "time_of_day": "time_of_day",
    "year": "year",
}
