"""
Runtime-generated Pydantic models from the canonical JSON Schema.

The JSON Schema (game_state.schema.json) is the SINGLE source of truth.
This Pydantic model is generated dynamically at import time to guarantee
it never diverges from the schema.

Real validation is performed by validate_game_state() via jsonschema.
This Pydantic model exists for to_model()/from_model() round-trip
serialization support only.

Previously this file contained 1100+ lines of static Pydantic models
auto-generated by datamodel-codegen. Those models diverged from the
JSON Schema over time (e.g. level capped at 20, Stats with extra="forbid",
Experience rejecting legacy integer format). The dynamic approach
eliminates this class of bugs entirely.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import BaseModel, ConfigDict

_SCHEMA_PATH = Path(__file__).parent / "game_state.schema.json"


def _load_schema() -> dict[str, Any]:
    """Load the canonical JSON Schema at import time."""
    with open(_SCHEMA_PATH, encoding="utf-8") as f:
        return json.load(f)


# Load schema once at import time to verify the file exists and is valid JSON.
_schema = _load_schema()


class GameState(BaseModel):
    """Complete game state model for WorldArchitect.AI.

    Uses extra='allow' so that ALL fields pass through without rejection.
    Real validation is done by validate_game_state() in validation.py
    via the JSON Schema, not by this Pydantic model.

    This model exists solely for to_model()/from_model() round-trip support,
    ensuring data fidelity (including None preservation) during serialization.
    """

    model_config = ConfigDict(extra="allow", arbitrary_types_allowed=True)
