/**
 * Streaming Client for WorldArchitect.AI
 *
 * Handles Server-Sent Events (SSE) for real-time LLM response streaming.
 * Allows users to see text chunks as they are generated by the LLM.
 *
 * @example
 * const streaming = new StreamingClient(campaignId);
 * streaming.onChunk = (chunk, fullText) => {
 *   appendToStoryPanel(chunk);
 * };
 * streaming.onComplete = (result) => {
 *   addToHistory(result.full_narrative);
 * };
 * await streaming.sendMessage("I attack the dragon", "character");
 */

class StreamingClient {
  /**
   * Create a new streaming client.
   * @param {string} campaignId - The campaign ID for API calls
   */
  constructor(campaignId) {
    this.campaignId = campaignId;
    this.abortController = null;
    this.fullText = '';
    this.isStreaming = false;
    this._currentRunId = null;

    // Event callbacks - override these to handle events
    this.onChunk = null; // (chunk: string, fullText: string) => void
    this.onToolStart = null; // (payload: {tool_name, arguments}) => void
    this.onToolResult = null; // (payload: {tool_name, result}) => void
    this.onStateUpdate = null; // (payload: object) => void
    this.onWarning = null; // (payload: {message}) => void
    this.onComplete = null; // (payload: {full_narrative, ...}) => void
    this.onError = null; // (payload: {message}) => void
    this.onStreamStart = null; // () => void
    this.onStreamEnd = null; // () => void
    this.onStatus = null; // (payload: {message, ...}) => void
    this.onMetadata = null; // (payload: object) => void
    this.onPlanningThinking = null; // (thinkingText: string) => void

    // Deduplication state for planning thinking extraction
    this._lastPlanningThinking = null;
    this._planningThinkingComplete = false;
  }

  /**
   * Send a message and stream the response.
   * @param {string} userInput - The user's action/input
   * @param {string} [mode='character'] - Interaction mode
   * @returns {Promise<void>}
   */
  async sendMessage(userInput, mode = 'character') {
    // Cancel any existing stream
    this.cancel();

    const runId = Symbol('stream-run');
    this._currentRunId = runId;
    this.fullText = '';
    this._lastPlanningThinking = null;
    this._planningThinkingComplete = false;
    this.isStreaming = true;
    this.abortController = new AbortController();

    if (this.onStreamStart) {
      this.onStreamStart();
    }

    try {
      // Get auth headers
      let headers = {
        'Content-Type': 'application/json',
      };

      if (window.authTokenManager) {
        if (typeof window.authTokenManager.waitForAuthInit === 'function') {
          await window.authTokenManager.waitForAuthInit();
        }
        try {
          const authHeaders = await window.authTokenManager.getAuthHeaders();
          headers = { ...headers, ...authHeaders };
        } catch (authError) {
          // Fallback path for transient auth races before headers are available.
          if (window.firebase && firebase.auth().currentUser) {
            const token = await firebase.auth().currentUser.getIdToken();
            headers['Authorization'] = `Bearer ${token}`;
          } else {
            throw authError;
          }
        }
      } else if (window.firebase && firebase.auth().currentUser) {
        const token = await firebase.auth().currentUser.getIdToken();
        headers['Authorization'] = `Bearer ${token}`;
      }

      const response = await fetch(
        `/api/campaigns/${this.campaignId}/interaction/stream`,
        {
          method: 'POST',
          headers: headers,
          body: JSON.stringify({ input: userInput, mode: mode }),
          signal: this.abortController.signal,
        },
      );

      if (!response.ok) {
        // Attempt to surface structured error payloads (e.g. rate limit metadata)
        // so the UI can provide actionable feedback instead of a generic status.
        let errorData = null;
        try {
          errorData = await response.json();
        } catch (e) {
          // Non-JSON error bodies (e.g. HTML) fall back to status-only message.
        }

        if (
          response.status === 429 &&
          errorData &&
          (errorData.error_type === 'rate_limit' || errorData.errorType === 'rate_limit') &&
          typeof window !== 'undefined' &&
          typeof window.showRateLimitModal === 'function'
        ) {
          const message = errorData.error || errorData.message || 'Rate limit reached.';
          const resetDaily = errorData.reset_time_daily || errorData.resetTimeDaily || null;
          const resetHourly = errorData.reset_time_hourly || errorData.resetTimeHourly || null;
          const resetTime = resetHourly || resetDaily || null;
          const resetType = resetHourly ? 'hourly' : resetDaily ? 'daily' : null;
          window.showRateLimitModal(message, resetTime, resetType);
        }

        throw new Error(
          (errorData && (errorData.error || errorData.message)) ||
          `HTTP error! status: ${response.status}`,
        );
      }

      if (!response.body) {
        throw new Error('Readable stream is not available on this response.');
      }

      // Read the stream
      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = '';

      while (true) {
        const { done, value } = await reader.read();

        if (done) {
          break;
        }

        // Decode the chunk and add to buffer
        buffer += decoder.decode(value, { stream: true });

        // Process complete SSE messages (ending with \n\n)
        const messages = buffer.split('\n\n');
        buffer = messages.pop() || ''; // Keep incomplete message in buffer

        for (const message of messages) {
          if (message.trim() && this._currentRunId === runId) {
            this._processSSEMessage(message, runId);
          }
        }
      }

      // Process any remaining buffer
      if (buffer.trim() && this._currentRunId === runId) {
        this._processSSEMessage(buffer, runId);
      }
    } catch (error) {
      if (error.name === 'AbortError') {
        console.log('Stream cancelled by user');
      } else if (this._currentRunId === runId) {
        console.error('Streaming error:', error);
        if (this.onError) {
          this.onError({ message: error.message });
        }
      }
    } finally {
      if (this._currentRunId === runId) {
        this.isStreaming = false;
        this.abortController = null;
        this._currentRunId = null;

        if (this.onStreamEnd) {
          this.onStreamEnd();
        }
      }
    }
  }

  /**
   * Process a single SSE message.
   * @param {string} message - The SSE message string
   * @private
   */
  _processSSEMessage(message, runId) {
    if (this._currentRunId !== runId) {
      return;
    }

    // SSE format: "data: {...}"
    const lines = message.split('\n');

    for (const line of lines) {
      if (line.startsWith('data: ')) {
        const rawData = line.slice(6); // Remove "data: " prefix
        try {
          const event = JSON.parse(rawData);
          this._handleEvent(event, runId);
        } catch (err) {
          // Gracefully handle malformed JSON in SSE data lines
          console.error('Failed to parse SSE data line as JSON:', rawData, err);
          if (this.onError) {
            this.onError({
              type: 'parse_error',
              message: 'Failed to parse SSE data line as JSON',
              raw: rawData,
              error: err instanceof Error ? err.message : String(err),
            });
          }
        }
      }
    }
  }

  /**
   * Handle a parsed SSE event.
   * @param {Object} event - The parsed event object
   * @private
   */
  _handleEvent(event, runId) {
    if (this._currentRunId !== runId) {
      return;
    }

    const { type, payload } = event;

    switch (type) {
      case 'chunk':
        this.fullText += payload.text || '';
        // Extract and emit planning thinking progressively before display text.
        // Empty thinking text is intentionally not displayed (truthy check).
        if (this.onPlanningThinking && !this._planningThinkingComplete) {
          const thinkingText = this._extractPlanningThinking(this.fullText);
          if (thinkingText && thinkingText !== this._lastPlanningThinking) {
            this._lastPlanningThinking = thinkingText;
            this.onPlanningThinking(thinkingText);
          }
        }
        const displayText = this._getStreamingDisplayText(this.fullText);
        if (this.onChunk) {
          this.onChunk(payload.text, displayText);
        }
        break;

      case 'tool_start':
        if (this.onToolStart) {
          this.onToolStart(payload);
        }
        break;

      case 'tool_result':
        if (this.onToolResult) {
          this.onToolResult(payload);
        }
        break;

      case 'state':
        if (this.onStateUpdate) {
          this.onStateUpdate(payload);
        }
        break;

      case 'status':
        if (this.onStatus) {
          this.onStatus(payload);
        }
        break;

      case 'metadata':
        if (this.onMetadata) {
          this.onMetadata(payload);
        }
        break;

      case 'phase_transition':
        if (payload && payload.reset_text) {
          this.fullText = '';
          this._lastPlanningThinking = null;
          this._planningThinkingComplete = false;
          if (this.onPlanningThinking) {
            this.onPlanningThinking('');
          }
          if (this.onChunk) {
            this.onChunk('', this.fullText);
          }
        }
        break;

      case 'done':
        if (this.onComplete) {
          const doneDisplayText =
            typeof payload?.display_text === 'string' ? payload.display_text : '';
          this.onComplete({
            ...payload,
            // Preserve explicit empty-string narratives (some modes display user-facing
            // text in other structured fields while keeping narrative empty).
            full_narrative:
              typeof payload?.full_narrative === 'string'
                ? payload.full_narrative
                : doneDisplayText || this.fullText,
            display_text: doneDisplayText || this.fullText,
          });
        }
        break;

      case 'error':
        console.error('Stream error event:', payload);
        if (this.onError) {
          this.onError(payload);
        }
        break;

      case 'warning':
        console.warn('Stream warning event:', payload);
        if (this.onWarning) {
          this.onWarning(payload);
        }
        break;

      default:
        console.warn('Unknown event type:', type, payload);
    }
  }

  /**
   * Extract narrative text from streamed JSON envelopes when possible.
   * Falls back to raw text if no narrative envelope can be detected yet.
   * @param {string} rawText
   * @returns {string}
   * @private
   */
  _getStreamingDisplayText(rawText) {
    const parsedNarrative = this._extractNarrativeFromParsedEnvelope(rawText);
    if (parsedNarrative !== null) {
      return parsedNarrative;
    }
    const partialNarrative = this._extractNarrativeFromRawEnvelope(rawText);
    if (partialNarrative !== null) {
      return partialNarrative;
    }
    if (this._looksLikeIncompleteStructuredEnvelope(rawText)) {
      // Avoid multi-second "Loading..." gaps while non-narrative fields stream first.
      return this._getStructuredEnvelopePlaceholder(rawText);
    }
    return rawText;
  }

  /**
   * Provide a safe, non-empty placeholder while we are receiving a JSON envelope
   * but can't extract narrative yet.
   * @param {string} rawText
   * @returns {string}
   * @private
   */
  _getStructuredEnvelopePlaceholder(rawText) {
    const text = typeof rawText === 'string' ? rawText : '';
    const fields = [];
    const knownFields = [
      'scene_header',
      'action_resolution',
      'resources',
      'rolls',
      'world_events',
      'faction_updates',
      'time_events',
      'rumors',
      'complications',
      'state_updates',
      'entities',
      'thinking',
      'planning_block',
    ];
    for (const field of knownFields) {
      const re = new RegExp(`\"${field}\"\\s*:`, 'i');
      if (re.test(text)) {
        fields.push(field);
      }
    }
    if (fields.length === 0) {
      return 'Generating structured response...';
    }
    const preview = fields.slice(0, 3).join(', ');
    const suffix = fields.length > 3 ? ', ...' : '';
    return `Generating structured response... (${preview}${suffix})`;
  }

  /**
   * Detect partially streamed JSON envelopes before narrative extraction is possible.
   * @param {string} rawText
   * @returns {boolean}
   * @private
   */
  _looksLikeIncompleteStructuredEnvelope(rawText) {
    const text = typeof rawText === 'string' ? rawText.trimStart() : '';
    if (!text) {
      return false;
    }

    // Some model outputs stream JSON inside markdown fences first.
    if (/^```(?:json)?/i.test(text)) {
      if (/"action_resolution"|"scene_header"|"resources"|"rolls"/.test(text)) {
        return true;
      }
    }

    // If we're clearly in schema keys before a narrative field, suppress envelope output.
    // god_mode_response is an alternative text field that should also unsuppress.
    if (
      /"action_resolution"|"scene_header"|"resources"|"rolls"/.test(text) &&
      !/"narrative"\s*:/.test(text) &&
      !/"god_mode_response"\s*:/.test(text)
    ) {
      return true;
    }

    if (text.startsWith('{') || text.startsWith('[')) {
      // Treat obvious JSON object/array prefixes as structured envelope chunks.
      if (/"[a-zA-Z_][a-zA-Z0-9_]*"\s*:/.test(text) || /"action_resolution"|"scene_header"|"resources"/.test(text)) {
        return true;
      }
    }
    return false;
  }

  /**
   * Parse complete JSON and extract narrative when available.
   * @param {string} rawText
   * @returns {string|null}
   * @private
   */
  _extractNarrativeFromParsedEnvelope(rawText) {
    try {
      const parsed = JSON.parse(rawText);
      const stringCandidates = [];
      if (typeof parsed?.god_mode_response === 'string') stringCandidates.push(parsed.god_mode_response);
      if (typeof parsed?.display_text === 'string') stringCandidates.push(parsed.display_text);
      if (typeof parsed?.narrative === 'string') stringCandidates.push(parsed.narrative);

      if (Array.isArray(parsed) && parsed.length > 0) {
        if (typeof parsed[0]?.god_mode_response === 'string') stringCandidates.push(parsed[0].god_mode_response);
        if (typeof parsed[0]?.display_text === 'string') stringCandidates.push(parsed[0].display_text);
        if (typeof parsed[0]?.narrative === 'string') stringCandidates.push(parsed[0].narrative);
      }

      if (typeof parsed?.response?.god_mode_response === 'string') stringCandidates.push(parsed.response.god_mode_response);
      if (typeof parsed?.response?.display_text === 'string') stringCandidates.push(parsed.response.display_text);
      if (typeof parsed?.response?.narrative === 'string') stringCandidates.push(parsed.response.narrative);

      for (const candidate of stringCandidates) {
        if (typeof candidate === 'string' && candidate.trim()) {
          return candidate;
        }
      }

      // Preserve explicit empty string only when no non-empty display field exists.
      for (const candidate of stringCandidates) {
        if (typeof candidate === 'string') {
          return candidate;
        }
      }
      return null;
    } catch (_err) {
      return null;
    }
  }

  /**
   * Extract partial narrative from in-progress JSON string payload.
   * @param {string} rawText
   * @returns {string|null}
   * @private
   */
  _extractNarrativeFromRawEnvelope(rawText) {
    const fieldPatterns = [
      /"god_mode_response"\s*:\s*"/g,
      /"display_text"\s*:\s*"/g,
      /"narrative"\s*:\s*"/g,
    ];

    const extractAt = (startIndex) => {
      let i = startIndex;
      let escaped = false;
      let out = '';

      while (i < rawText.length) {
        const ch = rawText[i];
        if (escaped) {
          switch (ch) {
            case 'n':
              out += '\n';
              break;
            case 't':
              out += '\t';
              break;
            case 'r':
              out += '\r';
              break;
            case '"':
              out += '"';
              break;
            case '\\':
              out += '\\';
              break;
            default:
              out += ch;
          }
          escaped = false;
        } else if (ch === '\\') {
          escaped = true;
        } else if (ch === '"') {
          return out;
        } else {
          out += ch;
        }
        i += 1;
      }

      return out;
    };

    const candidates = [];
    for (const pattern of fieldPatterns) {
      let match = null;
      while ((match = pattern.exec(rawText)) !== null) {
        if (match.index === undefined) continue;
        candidates.push({
          index: match.index,
          text: extractAt(match.index + match[0].length),
        });
      }
    }

    if (candidates.length === 0) {
      return null;
    }

    for (const candidate of candidates) {
      if (typeof candidate.text === 'string' && candidate.text.trim()) {
        return candidate.text;
      }
    }

    // If all extracted fields are empty so far, keep legacy behavior by returning
    // the earliest matched field's current value (often empty until more chunks arrive).
    candidates.sort((a, b) => a.index - b.index);
    return candidates[0].text;
  }

  /**
   * Extract planning_block.thinking text from partial JSON stream.
   * Uses the same character-walking approach as _extractNarrativeFromRawEnvelope
   * to handle incomplete JSON safely.
   * @param {string} rawText
   * @returns {string|null}
   * @private
   */
  _extractPlanningThinking(rawText) {
    // Look for "thinking" key inside a planning_block context.
    // The LLM typically emits: {"planning_block":{"thinking":"..."
    // Use global flag to iterate past any "thinking" keys outside planning_block.
    const pattern = /"thinking"\s*:\s*"/g;
    let match;
    while ((match = pattern.exec(rawText)) !== null) {
      if (this._isEscapedQuote(rawText, match.index)) {
        continue;
      }

      // Only extract if this match is inside an open planning_block object.
      // Require depth === 1 so nested thinking keys do not mask
      // the canonical planning_block.thinking field.
      const planningDepth = this._getPlanningBlockDepthAtPosition(rawText, match.index);
      if (planningDepth !== 1) {
        continue;
      }

      // Walk the string from match end, handling JSON escape sequences
      let i = match.index + match[0].length;
      let escaped = false;
      let out = '';

      while (i < rawText.length) {
        const ch = rawText[i];
        if (escaped) {
          switch (ch) {
            case 'n': out += '\n'; break;
            case 't': out += '\t'; break;
            case 'r': out += '\r'; break;
            case '"': out += '"'; break;
            case '\\': out += '\\'; break;
            default: out += ch;
          }
          escaped = false;
        } else if (ch === '\\') {
          escaped = true;
        } else if (ch === '"') {
          // Closing quote found — return complete thinking text
          this._planningThinkingComplete = true;
          return out;
        } else {
          out += ch;
        }
        i += 1;
      }

      // No closing quote yet — return partial text (still streaming)
      return out || null;
    }

    return null;
  }

  /**
   * Check whether a quote at index is escaped with an odd number of backslashes.
   * @param {string} text
   * @param {number} quoteIndex
   * @returns {boolean}
   * @private
   */
  _isEscapedQuote(text, quoteIndex) {
    let backslashCount = 0;
    for (let i = quoteIndex - 1; i >= 0 && text[i] === '\\'; i--) {
      backslashCount++;
    }
    return backslashCount % 2 === 1;
  }

  /**
   * Return planning_block nesting depth at a position in raw text.
   * Depth 1 means the candidate key is directly inside planning_block.
   * @param {string} text - The full raw text
   * @param {number} position - The position of the thinking key we're checking
   * @returns {number}
   * @private
   */
  _getPlanningBlockDepthAtPosition(text, position) {
    // Find ALL planning_block occurrences before the position
    const prefix = text.substring(0, position);
    const pattern = /"planning_block"\s*:\s*\{/g;
    const matches = [];
    let match;
    while ((match = pattern.exec(prefix)) !== null) {
      if (this._isEscapedQuote(prefix, match.index)) {
        continue;
      }
      matches.push(match);
    }

    if (matches.length === 0) {
      return 0;
    }

    // Iterate backwards to find the innermost (most recent) planning_block
    for (let m = matches.length - 1; m >= 0; m--) {
      const planningMatch = matches[m];

      // Count braces from after "planning_block":{ to the position
      // Start with depth = 1 because we're INSIDE the planning_block's opening brace
      let depth = 1;
      let inString = false;
      let escaped = false;

      for (
        let i = planningMatch.index + planningMatch[0].length;
        i < position;
        i++
      ) {
        const ch = text[i];

        if (escaped) {
          escaped = false;
          continue;
        }

        if (ch === '\\') {
          escaped = true;
          continue;
        }

        if (ch === '"') {
          inString = !inString;
          continue;
        }

        if (inString) {
          continue;
        }

        if (ch === '{') {
          depth++;
        } else if (ch === '}') {
          depth--;
          if (depth <= 0) {
            // This planning_block is closed, try the previous one
            break;
          }
        }
      }

      // If this planning_block is still open (depth > 0), return depth at position
      if (depth > 0) {
        return depth;
      }
      // Otherwise, this planning_block was closed, continue to check previous one
    }

    return 0;
  }

  /**
   * Cancel the current stream.
   */
  cancel() {
    if (this.abortController) {
      this.abortController.abort();
      this.abortController = null;
    }
    this.isStreaming = false;
  }

  /**
   * Check if currently streaming.
   * @returns {boolean}
   */
  isActive() {
    return this.isStreaming;
  }
}

/**
 * Render planning thinking text using the same structure/classes as the final UI.
 *
 * @param {HTMLElement | null} container
 * @param {string} thinkingText
 */
function renderPlanningThinkingBlock(container, thinkingText) {
  if (!container) return;

  const normalizedText =
    typeof thinkingText === 'string' ? thinkingText.trim() : '';

  if (!normalizedText) {
    container.style.display = 'none';
    container.textContent = '';
    return;
  }

  container.style.display = 'block';
  container.textContent = '';

  const thinkingDiv = document.createElement('div');
  thinkingDiv.className = 'planning-block-thinking';

  const label = document.createElement('strong');
  label.textContent = '🤔 Planning:';

  const textSpan = document.createElement('span');
  textSpan.className = 'planning-thinking-text';
  textSpan.textContent = normalizedText;

  thinkingDiv.appendChild(label);
  thinkingDiv.appendChild(document.createTextNode(' '));
  thinkingDiv.appendChild(textSpan);
  container.appendChild(thinkingDiv);
}

/**
 * Create a streaming-enabled interaction handler.
 * This is a drop-in enhancement for existing interaction forms.
 *
 * @param {Object} options - Configuration options
 * @param {string} options.campaignId - Campaign ID
 * @param {HTMLElement} options.storyContainer - Container for story content
 * @param {HTMLElement} options.inputElement - User input element
 * @param {HTMLElement} options.spinnerElement - Loading spinner element
 * @param {Function} options.getMode - Function to get current interaction mode
 * @param {Function} options.appendToStory - Function to append final story entry
 * @param {boolean} [options.useStreaming=true] - Whether to use streaming
 * @returns {Object} Handler with sendMessage method
 */
function createStreamingHandler(options) {
  const {
    campaignId,
    storyContainer,
    inputElement,
    spinnerElement,
    getMode,
    appendToStory,
    useStreaming = true,
  } = options;

  // Check if streaming is enabled via localStorage preference
  const streamingEnabled =
    useStreaming && localStorage.getItem('useStreaming') !== 'false';

  if (!streamingEnabled) {
    return null; // Fall back to regular handler
  }

  const client = new StreamingClient(campaignId);
  let streamingElement = null;

  const _renderFinalEntryInPlace = (payload) => {
    if (!streamingElement) {
      return;
    }

    const fullNarrative =
      typeof payload?.full_narrative === 'string' ? payload.full_narrative : '';
    const sceneLabel =
      payload?.user_scene_number != null
        ? `Scene #${payload.user_scene_number}`
        : 'Story';
    const resourcesText =
      typeof payload?.resources === 'string' ? payload.resources : null;

    // SECURITY: Never inject model output into innerHTML.
    // Use DOM nodes + textContent to prevent XSS and keep rendering deterministic.
    streamingElement.textContent = '';

    if (resourcesText && resourcesText.trim()) {
      const resourcesDiv = document.createElement('div');
      resourcesDiv.className = 'resources';
      const strong = document.createElement('strong');
      strong.textContent = '📊 Resources:';
      const text = document.createTextNode(` ${resourcesText}`);
      resourcesDiv.appendChild(strong);
      resourcesDiv.appendChild(text);
      streamingElement.appendChild(resourcesDiv);
    }

    const p = document.createElement('p');
    const labelStrong = document.createElement('strong');
    labelStrong.textContent = `${sceneLabel}:`;
    const narrativeText = document.createTextNode(` ${fullNarrative}`);
    p.appendChild(labelStrong);
    p.appendChild(narrativeText);
    streamingElement.appendChild(p);
  };

  client.onStreamStart = () => {
    // Create a temporary element for streaming content
    streamingElement = document.createElement('div');
    streamingElement.className = 'story-entry streaming-entry';
    streamingElement.innerHTML =
      '<p><strong>Story:</strong> <span class="streaming-text">Loading story...</span><span class="streaming-cursor">▌</span></p>' +
      '<div class="streaming-planning-thinking planning-block" style="display:none;"></div>';
    storyContainer.appendChild(streamingElement);

    // Show spinner
    if (spinnerElement) {
      spinnerElement.style.display = 'block';
    }

    // Disable input
    if (inputElement) {
      inputElement.disabled = true;
    }
  };

  client.onPlanningThinking = (thinkingText) => {
    if (!streamingElement) return;
    const container = streamingElement.querySelector('.streaming-planning-thinking');
    renderPlanningThinkingBlock(container, thinkingText);
  };

  client.onChunk = (chunk, fullText) => {
    // Append chunk to streaming element
    if (streamingElement) {
      const textSpan = streamingElement.querySelector('.streaming-text');
      if (textSpan) {
        textSpan.textContent = fullText || 'Loading story...';
      }
    }
  };

  client.onToolResult = (payload) => {
    if (!streamingElement) {
      return;
    }

    // Clear any active "running tool" indicators once a result arrives.
    const runningStatuses = streamingElement.querySelectorAll('[data-tool-status="running"]');
    runningStatuses.forEach((status) => {
      status.remove();
    });

    const toolName = payload.tool_name || 'unknown';

    // Show dice roll animation/results
    if (toolName === 'roll_dice') {
      const rollDiv = document.createElement('div');
      rollDiv.className = 'dice-roll-inline';
      const icon = document.createElement('span');
      icon.className = 'dice-icon';
      icon.textContent = '🎲';
      const resultSpan = document.createElement('span');
      const rollText =
        typeof payload.result === 'string'
          ? payload.result
          : JSON.stringify(payload.result);
      resultSpan.textContent = ` ${rollText}`;
      rollDiv.appendChild(icon);
      rollDiv.appendChild(resultSpan);
      streamingElement.insertBefore(rollDiv, streamingElement.firstChild);
      return;
    }

    // Faction tools get a richer inline summary for live strategy visibility.
    if (toolName.startsWith('faction_')) {
      const factionDiv = document.createElement('div');
      factionDiv.className = 'tool-result-inline faction-tool-result';
      const powerChange = payload?.result?.power_change;
      const suffix =
        typeof powerChange === 'number'
          ? ` (power_change: ${powerChange})`
          : '';
      factionDiv.textContent = `Faction update: ${toolName}${suffix}`;
      streamingElement.insertBefore(factionDiv, streamingElement.firstChild);
      return;
    }

    const toolDiv = document.createElement('div');
    toolDiv.className = 'tool-result-inline';
    toolDiv.textContent = `Tool ${toolName} executed`;
    streamingElement.insertBefore(toolDiv, streamingElement.firstChild);
  };

  client.onToolStart = (payload) => {
    if (!streamingElement) {
      return;
    }
    const toolName = payload.tool_name || 'tool';
    const statusDiv = document.createElement('div');
    statusDiv.className = 'tool-status-inline text-muted';
    statusDiv.textContent = `Running ${toolName}...`;
    statusDiv.setAttribute('data-tool-status', 'running');
    statusDiv.setAttribute('data-tool-name', toolName);
    streamingElement.insertBefore(statusDiv, streamingElement.firstChild);
  };

  client.onStateUpdate = (payload) => {
    if (!streamingElement || !payload || typeof payload !== 'object') {
      return;
    }
    const stateDiv = document.createElement('div');
    stateDiv.className = 'state-update-inline text-muted';
    stateDiv.textContent = `State updated: ${Object.keys(payload).join(', ')}`;
    streamingElement.insertBefore(stateDiv, streamingElement.firstChild);
  };

  client.onWarning = (payload) => {
    if (!streamingElement) {
      return;
    }
    const warningDiv = document.createElement('div');
    warningDiv.className = 'stream-warning-inline text-warning';
    warningDiv.textContent = payload?.message || 'Streaming warning';
    streamingElement.appendChild(warningDiv);
  };

  client.onComplete = (payload) => {
    // Remove streaming cursor
    if (streamingElement) {
      const cursor = streamingElement.querySelector('.streaming-cursor');
      if (cursor) {
        cursor.remove();
      }
      streamingElement.classList.remove('streaming-layout', 'streaming-entry');
    }

    // Finalize in place to avoid remove-and-reappend visual replacement.
    const structured = payload?.structured_response;
    const structuredGodModeText =
      typeof structured?.god_mode_response === 'string'
        ? structured.god_mode_response
        : '';

    let narrative =
      typeof payload?.full_narrative === 'string'
        ? payload.full_narrative
        : typeof payload?.narrative === 'string'
          ? payload.narrative
          : typeof payload?.response === 'string'
            ? payload.response
            : '';

    if (
      typeof narrative === 'string' &&
      !narrative.trim() &&
      structuredGodModeText.trim()
    ) {
      narrative = structuredGodModeText;
    }

    if (streamingElement) {
      _renderFinalEntryInPlace({ ...payload, full_narrative: narrative });
      return;
    }

    if (appendToStory) {
      // Backward-compatibility fallback for legacy payload shapes.
      appendToStory(
        'gemini',
        narrative,
        null,
        false,
        payload?.user_scene_number,
        payload?.structured_response || payload,
      );
    }
  };

  client.onError = (payload) => {
    const message = payload?.message || 'Unknown streaming error';
    console.error('Streaming error:', message);
    if (streamingElement) {
      const errorParagraph = document.createElement('p');
      errorParagraph.className = 'text-danger';
      errorParagraph.textContent = `Error: ${message}`;
      streamingElement.innerHTML = '';
      streamingElement.appendChild(errorParagraph);
    }
  };

  client.onStreamEnd = () => {
    // Hide spinner
    if (spinnerElement) {
      spinnerElement.style.display = 'none';
    }

    // Re-enable input
    if (inputElement) {
      inputElement.disabled = false;
      inputElement.focus();
    }

    streamingElement = null;
  };

  return {
    sendMessage: async (userInput) => {
      const mode = getMode ? getMode() : 'character';
      await client.sendMessage(userInput, mode);
    },
    cancel: () => client.cancel(),
    isActive: () => client.isActive(),
  };
}

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = {
    StreamingClient,
    createStreamingHandler,
    renderPlanningThinkingBlock,
  };
}

// Make available globally
window.StreamingClient = StreamingClient;
window.createStreamingHandler = createStreamingHandler;
window.renderPlanningThinkingBlock = renderPlanningThinkingBlock;
